### PR TITLE
Fixes compilation in recent environments 

### PR DESCRIPTION
**Pull request by mslazynski**
"restrict" should not be use a variable name.

### CODE REVIEW

**Comment by pquentin** [comment]
@rorchard thoughts? sounds like a great pull request to me :)

**Comment by rorchard** [comment]
Sorry, I haven’t been checking the Github site recently. Sounds like someone has fixed some problems to make things work again in newer 
versions of software and operating environments. This would be very useful. Retirement has taken too much of my time lately!

Bob.

**Comment by pquentin** [comment]
No worries. :)

I just noticed I have commit access. If it's on purpose, I can check the pull request works and merge it myself.

**Comment by rorchard** [comment]
I’d be pleased if you did the merge. If there are problems I’ll give you access.

**Comment by pquentin** [comment]
Thank you @mslazynski! Merged your pull request.

**Pull request merged**
